name: Morning Weather

on:
  schedule:
    # 03:53 MSK = 00:53 UTC
    - cron: '53 0 * * *'
  
  # Кнопка для ручного запуска в Actions
  workflow_dispatch:

jobs:
  send-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install requests

      - name: Run Weather Bot
        env:
          WEATHER_TG_BOT_TOKEN: ${{ secrets.WEATHER_TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python weather_bot.py

